# What is machine learning?

*Authors: [Natalie G. Nelson](https://bae.ncsu.edu/people/nnelson4/), [Shih-Ni Prim](https://www.linkedin.com/in/shih-ni-prim-14033336/), [Sheila Saia](https://sheilasaia.rbind.io/), [Khara Grieger](https://cals.ncsu.edu/applied-ecology/people/kdgriege/), [Anders Huseth](https://cals.ncsu.edu/entomology-and-plant-pathology/people/ashuseth/), [Brian Reich](https://statistics.sciences.ncsu.edu/people/bjreich/)*

Machine learning methods teach computer models to make predictions from patterns in data (Zhi et al., 2024)[https://doi.org/10.1038/s44221-024-00202-z]. To find patterns in data, many, many mathematical calculations are involved. Computers are needed to develop machine learning models, and advances in computing gave rise to machine learning.  

## How is machine learning useful for natural resources management?
Historically, environmental and agricultural systems were primarily modeled with “process-based” or “mechanistic” models, which are models that simulate key system processes based on their underlying physics, chemistry, or biology [(Haefner 2005)](https://link.springer.com/book/10.1007/b106568). Models were often used to fill gaps in direct measurements of various environmental and agricultural phenomena. In the past, collecting any type of environmental or agricultural data was grueling, time consuming, and done by people. Today, some variables still require tough and tedious work to measure, but many variables are now readily measured with sensors and other automated instruments.
As an example of how process-based models are used, let’s consider the flow of water through an open channel. If you were estimating the velocity of water through an open channel using a process-based approach, you may use [Manning’s Equation](https://www.weather.gov/aprfc/normaldepthcalc), which simulates water velocity as a function of the channel’s physical properties like its slope and cross sectional area. To apply Manning’s Equation, you would have to take measurements of the channel’s dimensions.

However, with machine learning, you do not have to simulate environmental and agricultural variables using underlying processes. Instead, you can create a model that makes predictions from patterns in data. Machine learning models require that you have some measurements of your *response* or *target* variable, which is the variable you are seeking to estimate. In our current example, water velocity in the channel is the target variable. You also need measurements of *predictor* variables, or variables that you will use to predict your response. 

As one hypothetical example, a machine learning model of water velocity in an open channel might make predictions based on images instead of physical channel properties. A camera could be situated towards the channel to take time-lapse photos every few minutes. A machine learning model could then be developed to predict water velocity based on the appearance of the water in the images. For a real-world example of this, check out Chapman et al. (2024), [Stage and discharge prediction from documentary time-lapse imagery](https://journals.plos.org/water/article?id=10.1371/journal.pwat.0000106), in *PLoS ONE*. 

To create such a machine learning model, water velocity measurements would be needed to create a *training set*, or data used to *train* or develop the machine learning model. The water velocity measurements would be collected at the same time as the images, so the images could then be directly related to water velocity measurements (i.e., when the image looks like this, the water velocity is that). The *predictor* variables would be derived from the images. A machine learning algorithm could be selected to search for patterns between the images – e.g., the shading/color of individual image pixels, relationships between neighboring pixels – and the water velocity measurements. Once these patterns are established, they can be used to estimate water velocity from new images as they are collected. Importantly, the image-based machine learning model knows nothing about the underlying physics controlling water velocity in the channel; it has simply learned that certain patterns in the images correspond to higher or lower water velocities.

Machine learning models can easily be expanded to include many different types of predictor variables. For example, the image-based machine learning model for water velocity could be further built out to include additional predictors like rainfall, irrigation, and time of year. The flexibility of machine learning models allows them to consider many diverse streams of information when learning patterns from which to make predictions. To see additional examples of machine learning models developed for natural resource management applications, see chapter 4.

## Pros and cons
Because they make predictions from correlative patterns between the predictor and response variables, machine learning models have parallels to simpler statistical models like linear regression. However, machine learning models consist of hundreds, thousands, or millions of individual equations, while a linear regression model consists of only one equation. Because of their many equations, [machine learning models are commonly considered “black boxes”](https://www.nature.com/news/can-we-open-the-black-box-of-ai-1.20731) since peering into a machine learning model can feel like looking into a pitch black box – you don’t precisely know what's inside. Methods now exist to help us illuminate machine learning black boxes, and the field of “interpretable” or “explainable” machine learning has made great strides in support of better understanding the inner workings of these models [(Samek et al., 2021)](https://doi.org/10.1109/JPROC.2021.3060483). Still, machine learning models are substantially more challenging to interpret than most other model alternatives. 

While challenges to interpretation are a clear pitfall of machine learning models, their complicated structures allow for them to pick up on relatively subtle or nuanced relationships between datasets, making them effective predictive tools. In many cases, machine learning models outperform process-based models (e.g., their predictions can have greater accuracy than the predictions from other models). The ability to create strong predictions is arguably the hallmark strength of machine learning. The previously described flexibility of being able to include many different diverse data types (e.g., images, sensor data, weather station observations) as predictors is also a key strength. But, because they do not necessarily account for underlying processes, machine learning models are at risk of spurious predictions, particularly if developed irresponsibly. In chapter 3, we include questions you can ask to evaluate whether a model was developed responsibly, and assess whether it is vulnerable to making spurious predictions.

## Classes of machine learning models
In the previous example on image-based predictions of water velocity, we summarized the use of a *supervised* learning approach. Simply put, supervised learning is when there are true answers for the model, or there are measurements for the response variable [(Sarker 2021)](https://doi.org/10.1007/s42979-021-00592-x). In the water velocity model example, water velocity measurements were used during model development to facilitate the learning of patterns in the images that could specifically be used to predict water velocity. Once a supervised learning model is developed, the predictions from the model can be compared with the measurements to assess how well the model predicts.

*Unsupervised* learning, on the other hand, performs tasks that do not have answers for the model. For example, instead of using the images of the stream to estimate water velocity, an unsupervised machine learning model could be used to group or cluster images with shared similarities. Unsupervised learning is often used as a computer-assisted way of exploring patterns in data  [(Sarker 2021)](https://doi.org/10.1007/s42979-021-00592-x). Sometimes, the groups or clusters uncovered by an unsupervised learning model can be assigned labels that are of use for other modeling or analysis efforts. 

## An example of supervised and unsupervised learning
The [National Land Cover Database or Dataset (NLCD)](https://www.usgs.gov/centers/eros/science/national-land-cover-database) is created by the U.S. Geological Survey and its partners to map land cover across the contiguous U.S. The data are updated every few years, creating a historical record of land cover change across the country over time. In the 1970s and 1980s, land cover mapping was performed by manually delineating areas from aerial photographs. In 1992, the NLCD premiered a land cover data product that was created from Landsat satellite imagery. Landsat imagery has pixels that are 30 meters by 30 meters. To create the 1992 product, NLCD imagery was clustered into 100 groups using an unsupervised learning approach, and people evaluated the 100 groups and manually assigned them to land cover categories (e.g., forest, developed area). Later, to create the 2001 NLCD product, a supervised learning approach was used in which areas of known land cover were used to train a model to predict land cover categories based on Landsat imagery. Read more about the history of the NLCD program in Chapter 18 of *The Nature of Geographic Information* [(DiBiase et al.)](https://www.e-education.psu.edu/natureofgeoinfo/).

## Algorithms
Within the two broad classifications of machine learning (supervised and unsupervised), there is an overwhelming number of machine learning *algorithms*, or specific computer model frameworks for implementing machine learning. The sheer number of machine learning algorithms attests to its power and versatility. This primer does not catalog different machine learning algorithms. As a starting point, you can see some algorithm examples at the resources below.
[Which machine learning algorithm should I use](https://blogs.sas.com/content/subconsciousmusings/2020/12/09/machine-learning-algorithm-use/) by SAS blogs
[Machine Learning Cheat Sheet](https://www.datacamp.com/cheat-sheet/machine-learning-cheat-sheet?utm_source=google&utm_medium=paid_search&utm_campaignid=19589720830&utm_adgroupid=157098107695&utm_device=c&utm_keyword=&utm_matchtype=&utm_network=g&utm_adpostion=&utm_creative=698229375346&utm_targetid=dsa-2264919291829&utm_loc_interest_ms=&utm_loc_physical_ms=9009732&utm_content=DSA~blog~Julia&utm_campaign=230119_1-sea~dsa~tofu_2-b2c_3-us_4-prc_5-na_6-na_7-le_8-pdsh-go_9-na_10-na_11-na-may24&gad_source=1&gclid=Cj0KCQjw6PGxBhCVARIsAIumnWai3I4X4UtrhM_2dA1pUpmAmC-iErsp57Cv6p4fEQugIVbGrx1VT2YaAsr7EALw_wcB) by Datacamp

## A deeper dive
If you would like to learn more about machine learning, check out [*An Introduction to Statistical Learning* by James et al. (2013)](https://www.statlearning.com/). This book provides a wealth of information on machine learning models, and the authors assume the readers are mainly interested in applying, rather than deeply studying, machine learning models. The four premises offered by the authors, listed on pp 8-9, demonstrate the practical focus of the book:
Many statistical learning methods are relevant and useful in a wide range of academic and non-academic disciplines, beyond just the statistical sciences.
Statistical learning should not be viewed as a series of black boxes.
While it is important to know what job is performed by each cog, it is not necessary to have the skills to construct the machine inside the box!
We presume that the reader is interested in applying statistical learning methods to real-world problems.
There are free PDF versions of the books [available online](https://www.statlearning.com/), and examples are presented in both R and Python. 