--- 
title: "A Machine Learning Primer for Natural Resource Management"
author: "Natalie Nelson, Shih-Ni Prim, et al."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: nataliegnelson/ml_primer
description: "This primer serves as a succinct guidebook on using machine learning in natural resources management."
---

# Welcome

From satellites to field-deployable sensors, the entire agricultural and environmental landscape is increasingly monitored. Advances in sensing allow for a wide range of variables to be measured at unprecedented rates and scales. The large amounts of data produced from agricultural and environmental systems are paving the way for data-intensive methods like machine learning and Artificial Intelligence to support decision-making in natural resources management. But these opportunities also create new educational needs, particularly among applied scientists and engineers who may not have received formal training in “data science” methods [(Saia et al., 2021)](https://doi.org/10.1016/j.ecolmodel.2020.109257), which is why we made this primer.

## How to use this primer
This primer serves as a succinct guidebook on using machine learning in natural resources management. It is written as a starting point, and not a comprehensive resource. 

All readers should start with chapter 2, which defines and describes “machine learning”. If you are not interested in developing machine learning models, and instead want to understand how to interpret machine learning models or critique tools that use machine learning, continue reading through chapters 3 and 4. If you are interested in seeing an example workflow for developing a machine learning model, skip to chapter 5. 

## Learning how to code
For those of you who are interested in developing machine learning models, the material presented in this primer will help show you where to start. In chapter 5, we include an example using code prepared in R, an open source statistical software environment. To learn more about coding in R, we recommend [R for Data Science](http://r4ds.hadley.nz/).

## Acknowledgements
Support for this primer was provided by the U.S. Department of Agriculture National Institute of Food and Agriculture grant number 2019-67021-29936.

## Citation
*Authors vary by chapter* (2024), A Machine Learning Primer for Natural Resources Management, Accessed online via go.ncsu.edu/mlprimer. 

## License
This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1).  
